// <auto-generated />
using System;
using BaseCore.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseCore.Repository.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260318080000_AddManufacturers")]
    partial class AddManufacturers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseCore.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new { Id = 1, Description = "Layered essentials for all seasons.", Name = "Outerwear", Slug = "outerwear" },
                        new { Id = 2, Description = "Everyday shirts, hoodies and tees.", Name = "Tops", Slug = "tops" },
                        new { Id = 3, Description = "Sneakers and boots with modern silhouettes.", Name = "Footwear", Slug = "footwear" },
                        new { Id = 4, Description = "Minimal accessories to complete the look.", Name = "Accessories", Slug = "accessories" },
                        new { Id = 5, Description = "Premium denim pieces built for comfort.", Name = "Denim", Slug = "denim" });
                });

            modelBuilder.Entity("BaseCore.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new { Id = 1,  Name = "FormAsh",     Country = "Vietnam",     Description = "Contemporary fashion label known for clean, structured pieces." },
                        new { Id = 2,  Name = "Urban Chill", Country = "USA",         Description = "Streetwear brand focused on comfortable, everyday essentials." },
                        new { Id = 3,  Name = "StreetStep",  Country = "South Korea", Description = "Minimalist footwear label built for urban environments." },
                        new { Id = 4,  Name = "BlueAura",    Country = "Japan",       Description = "Premium denim and outerwear manufacturer." },
                        new { Id = 5,  Name = "LoomLyfe",    Country = "Vietnam",     Description = "Handcrafted accessories made from sustainable natural materials." },
                        new { Id = 6,  Name = "Denim House", Country = "USA",         Description = "Dedicated denim label with a focus on fit and durability." },
                        new { Id = 7,  Name = "Rainform",    Country = "UK",          Description = "Technical outerwear brand built for city rain." },
                        new { Id = 8,  Name = "CalmThread",  Country = "Vietnam",     Description = "Basics brand focused on premium fabric and minimal design." },
                        new { Id = 9,  Name = "Pace",        Country = "USA",         Description = "Footwear brand for active urban lifestyles." },
                        new { Id = 10, Name = "BuckleCo",    Country = "Italy",       Description = "Leather accessories crafted with Italian hardware." });
                });

            modelBuilder.Entity("BaseCore.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BaseCore.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1,  Brand = "FormAsh",     CategoryId = 1, ManufacturerId = 1,  Description = "A relaxed-fit blazer with clean lines and comfortable layering for street-ready styling.",   Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1594938298603-c8148c4b4545?auto=format&fit=crop&w=900&q=80", IsNew = true,  Name = "Relaxed Blazer",      OriginalPrice = 1850000m, Price = 1450000m, Slug = "relaxed-blazer",      Stock = 16 },
                        new { Id = 2,  Brand = "Urban Chill", CategoryId = 2, ManufacturerId = 2,  Description = "Soft cotton tee with a subtle retro print and a relaxed silhouette.",                        Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=900&q=80", IsNew = true,  Name = "Vintage Graphic Tee", OriginalPrice = 550000m,  Price = 420000m,  Slug = "vintage-graphic-tee", Stock = 38 },
                        new { Id = 3,  Brand = "StreetStep",  CategoryId = 3, ManufacturerId = 3,  Description = "Minimal sneakers built with durable leather and cushioning for all-day comfort.",            Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80", IsNew = false, Name = "Classic Sneakers",    OriginalPrice = 1080000m, Price = 980000m,  Slug = "classic-sneakers",    Stock = 24 },
                        new { Id = 4,  Brand = "BlueAura",    CategoryId = 5, ManufacturerId = 4,  Description = "A classic denim jacket with a soft washed finish and durable stitching.",                    Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1523381210434-271e8be8a52f?auto=format&fit=crop&w=900&q=80", IsNew = false, Name = "Denim Jacket",        OriginalPrice = 1490000m, Price = 1320000m, Slug = "denim-jacket",        Stock = 12 },
                        new { Id = 5,  Brand = "LoomLyfe",    CategoryId = 4, ManufacturerId = 5,  Description = "A spacious woven tote that combines casual style with everyday function.",                    Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80", IsNew = false, Name = "Woven Tote Bag",      OriginalPrice = 620000m,  Price = 520000m,  Slug = "woven-tote-bag",      Stock = 45 },
                        new { Id = 6,  Brand = "Denim House", CategoryId = 5, ManufacturerId = 6,  Description = "Relaxed wide-leg jeans with a high-rise waist for a modern silhouette.",                     Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80", IsNew = false, Name = "Wide Leg Jeans",      OriginalPrice = 1100000m, Price = 960000m,  Slug = "wide-leg-jeans",      Stock = 30 },
                        new { Id = 7,  Brand = "Rainform",    CategoryId = 1, ManufacturerId = 7,  Description = "Oversized trench coat with water-resistant finish and modern utility details.",               Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=900&q=80", IsNew = true,  Name = "Utility Trench Coat", OriginalPrice = 2250000m, Price = 1850000m, Slug = "utility-trench-coat", Stock = 20 },
                        new { Id = 8,  Brand = "CalmThread",  CategoryId = 2, ManufacturerId = 8,  Description = "Crewneck sweatshirt with premium fleece lining and a clean logo-free look.",                 Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80", IsNew = false, Name = "Premium Sweatshirt",  OriginalPrice = 780000m,  Price = 650000m,  Slug = "premium-sweatshirt",  Stock = 27 },
                        new { Id = 9,  Brand = "Pace",        CategoryId = 3, ManufacturerId = 9,  Description = "High-top canvas sneakers with bold stitching and versatile street styling.",                  Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=900&q=80", IsNew = false, Name = "High-Top Sneakers",   OriginalPrice = 920000m,  Price = 890000m,  Slug = "high-top-sneakers",   Stock = 18 },
                        new { Id = 10, Brand = "BuckleCo",    CategoryId = 4, ManufacturerId = 10, Description = "Minimal leather belt with matte hardware, designed to pair with denim and dress pants.",     Gender = "Unisex", ImageUrl = "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", IsNew = false, Name = "Leather Belt",        OriginalPrice = 420000m,  Price = 360000m,  Slug = "leather-belt",        Stock = 60 });
                });

            modelBuilder.Entity("BaseCore.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderDetail", b =>
                {
                    b.HasOne("BaseCore.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BaseCore.Entities.Product", b =>
                {
                    b.HasOne("BaseCore.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("BaseCore.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
